fix(FEC-10455): incorrect order in reset and destroy process
kaltura/kaltura-player-js pull request #353
Opened 2020-09-01 15:51 UTC by Yuvalke

### Description of the Changes

Issue: player.destroy() sending invalid 'stop' bookmark with position val 0
Solution: reorder the compenet destroy since some of them depend on playkit.

Solve: FEC-10455.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2020-09-01 15:59 UTC, OrenMe requested changes
changing the order will most likely have implications.
I think moving the plugin manager to be before the local player is ok cause before the plugin manager changes it was almost first in playkit-js, but ui wrapper in reset I don't think so and for the destroy it might also be a drastic change.

In general I agree that all managers beside event need to be destroyed before player - but please check the implications so we don't have dependencies between components in destruction order.
@yairans please also review as you were the last one to touch this AFAICR

2020-09-01 17:03 UTC, Yuvalke commented
> changing the order will most likely have implications.
> I think moving the plugin manager to be before the local player is ok cause before the plugin manager changes it was almost first in playkit-js, but ui wrapper in reset I don't think so and for the destroy it might also be a drastic change.
> 
> In general I agree that all managers beside event need to be destroyed before player - but please check the implications so we don't have dependencies between components in destruction order.
> @yairans please also review as you were the last one to touch this AFAICR

@OrenMe I did check for Playlist Pugins and UI, all of them depend on playkit and UI and plugins used playkit on destroy/reset on the other hand playkit doesn't depend on none of them, same as each one in another so I think it's safe.

2020-09-01 19:28 UTC, yairans approved these changes

2020-09-02 04:45 UTC, OrenMe approved these changes
Ok, LGTM.

2020-09-02 06:39 UTC, merged