feat(FEC-10387): add support for referenceId filter in provider
kaltura/kaltura-player-js pull request #369
Opened 2020-11-03 21:00 UTC by RoyBregman

### Description of the Changes

Updating docs to support media loading with referenceId instead of entryId

solves FEC-10387

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [X] Docs have been updated

2020-11-04 08:10 UTC, yairans commented
@RoyBregman What's about analytics?
This field I believe should be passed on the plugin config using the evaluation mechanism.

2020-11-04 09:42 UTC, RoyBregman commented
> @RoyBregman What's about analytics?
> This field I believe should be passed on the plugin config using the evaluation mechanism.
> Then need to consider it in the analytics plugins

Awesome question, checked it now and it is okay. Uses the entryId from the response

2020-11-04 13:16 UTC, yairans submitted a review, later dismissed

2020-11-22 11:44 UTC, OrenMe requested changes
change title to `docs` if this is just docs.
Need to explain order of importance between entry and reference id.

2020-11-25 11:09 UTC, OrenMe submitted a review, later dismissed

2020-11-25 11:47 UTC, OrenMe approved these changes

2020-11-25 11:48 UTC, merged