feat(FEC-10766): create text config section and option for styling
kaltura/kaltura-player-js pull request #387
Opened 2020-12-08 14:26 UTC by Yuvalke

### Description of the Changes

Issue: text track doesn't have a config for styling, there is only an API for styling.
Solution: create a text container for the text track and add the options for styling the text track.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2020-12-27 14:16 UTC, RoyBregman commented on test/src/utils/test-utils.js
> -      enableCEA708Captions: true,
Maybe leave this test to check backward compatibility and add a comment to mention that?

2020-12-27 14:19 UTC, OrenMe submitted a review, later dismissed

2020-12-27 14:19 UTC, RoyBregman commented on test/src/utils/test-utils.js
> -      enableCEA708Captions: true,
Oh, but its one config for all tests... Nevermind

2020-12-28 15:40 UTC, OrenMe approved these changes

2020-12-28 15:41 UTC, OrenMe requested changes

2020-12-28 15:41 UTC, OrenMe commented on src/kaltura-player.js
> +  get textDisplaySetting(): Object {
move next to its setter

2020-12-29 13:53 UTC, OrenMe submitted a review, later dismissed

2020-12-29 14:06 UTC, OrenMe approved these changes

2020-12-29 14:09 UTC, merged