fix(FEC-10806): Playlist has limitation which configure cause setMedia
kaltura/kaltura-player-js pull request #390
Opened 2020-12-20 12:57 UTC by Yuvalke

### Description of the Changes

Issue: setMedia called before plugins initialize.
Solution: split the configure for one without sources and another one after with sources, as we do for sources as well.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2020-12-20 13:30 UTC, OrenMe requested changes
@Yuvalke please check failing tests and flow

2020-12-20 13:48 UTC, Yuvalke commented
> @Yuvalke please check failing tests and flow

@OrenMe tests don't pass since yair's change

2020-12-27 09:33 UTC, OrenMe commented
@yairans PTAL

2020-12-27 11:59 UTC, yairans approved these changes

2020-12-27 12:29 UTC, yairans approved these changes

2020-12-27 12:35 UTC, merged