fix(FEC-10994): Invalid version reported by players
kaltura/kaltura-player-js pull request #452
Opened 2021-05-30 09:37 UTC by Yuvalke

### Description of the Changes

Issue: some clients load the JS script with one uiconf but use another one in the call to setup or they don't provide it at all.
Solution: always take the uiconf config from the bundle object.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2021-05-31 10:17 UTC, yairans requested changes

2021-05-31 10:17 UTC, yairans commented on src/common/utils/setup-helpers.js
>    if (defaultOptions.provider.uiConfId) {
we want to support also when uiconf id no passed from the app. so can remove this if

2021-05-31 14:23 UTC, yairans approved these changes

2021-05-31 14:25 UTC, yairans commented
@Yuvalke please add the server change url in the desc

2021-06-02 04:08 UTC, OrenMe approved these changes

2021-07-01 06:19 UTC, merged