feat(FEC-11738): Related Entries - Phase 1
kaltura/kaltura-player-js pull request #511
Opened 2022-01-05 16:47 UTC by SivanA-Kaltura

### Description of the Changes

Add related content grid.
Related PRs:
https://github.com/kaltura/playkit-js-related/pull/1

Fixes FEC-11738.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2022-01-12 08:49 UTC, yairans requested changes

2022-01-12 11:09 UTC, SivanA-Kaltura commented on src/common/related/related-event-type.js
> +  RELATED_ITEM_CHANGED: `${namespace}-relateditemchanged`
it's a leftover from using the playlist api in ui, I'll just remove it and add it again when I need it

2022-01-12 12:05 UTC, yairans submitted a review, later dismissed

2022-01-16 09:07 UTC, yairans approved these changes

2022-01-16 16:43 UTC, merged