feat(FEC-12613): Image Entry - Kava Analytics Events
kaltura/kaltura-player-js pull request #604
Opened 2023-02-06 12:58 UTC by JonathanTGold

### Description of the Changes

Add isImg public API for let the Analytics plugins knowing the playback type

solves FEC-12613

related pr: 
https://github.com/kaltura/playkit-js-kava/pull/135

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2023-02-06 14:55 UTC, SivanA-Kaltura requested changes

2023-02-06 14:55 UTC, SivanA-Kaltura commented on src/kaltura-player.js
> +  isImg(): boolean {
i think isImage is better

2023-02-08 13:22 UTC, JonathanTGold commented on src/kaltura-player.js
> +  isImg(): boolean {
done

2023-02-08 14:25 UTC, SivanA-Kaltura approved these changes

2023-02-08 14:40 UTC, merged