feat: handle onPresetChange in plugins
kaltura/kaltura-player-js pull request #660
Opened 2023-10-17 11:38 UTC by lianbenjamin

### Description of the Changes

add handler for when preset change in plugins.

### CheckLists

- [ ] changes have been done against master branch, and PR does not conflict
- [ ] new unit / functional tests have been added (whenever applicable)
- [ ] test are passing in local environment
- [ ] Travis tests are passing (or test results are not worse than on master branch :))
- [ ] Docs have been updated

2023-10-17 12:26 UTC, SivanA-Kaltura requested changes

2023-10-17 12:26 UTC, SivanA-Kaltura commented on src/common/plugins/plugin-manager.js
> +    Object.keys(this._plugins).forEach(k => this._plugins[k].onPresetChange(oldPreset, newPreset));
maybe change k to pluginName

2023-10-17 12:26 UTC, SivanA-Kaltura commented on src/common/plugins/plugin-manager.js
>      Object.keys(this._plugins).forEach(k => this._plugins[k].loadMedia());
maybe change k to pluginName

2023-10-19 10:38 UTC, lianbenjamin commented
closing PR as it was fixed in a different way.

2023-10-19 10:38 UTC, closed without merging