feat(FEC-13540): allow passing entry id to start playing the playlist from
kaltura/kaltura-player-js pull request #688
Opened 2024-01-04 09:37 UTC by lianbenjamin

### Description of the Changes

- **enhancement**

Add the ability to pass an entryId, to playlist API, which the playlist will start playing from.

#### Resolves FEC-13540

2024-01-04 13:20 UTC, SivanA-Kaltura commented on src/common/playlist/playlist-manager.ts
>          );
looks good, just note the lint errors

2024-01-04 14:02 UTC, SivanA-Kaltura submitted a review, later dismissed

2024-01-23 10:27 UTC, SivanA-Kaltura commented
@lianbenjamin the .idea files were added by mistake ?

2024-01-23 10:28 UTC, lianbenjamin commented
@SivanA-Kaltura were added when i merged from master into branch.

2024-01-23 11:00 UTC, semarche-kaltura commented on .idea/.gitignore
do we need all those .idea files?

2024-01-23 11:01 UTC, semarche-kaltura commented on coverage/Chrome Headless 119.0.6045.159 (Mac OS 10.15.7)/base.css
I believe coverage folder should be ignored by git

2024-01-23 11:02 UTC, semarche-kaltura commented on demo/index.html
revert changes for demo page

2024-01-23 11:03 UTC, semarche-kaltura commented on demo/style.css
> +/*xs - 380 x 209*/
revert

2024-01-23 11:03 UTC, semarche-kaltura commented on samples/playkit-kaltura-cuepoints.js
revert

2024-01-23 11:03 UTC, semarche-kaltura commented on samples/playkit-kaltura-cuepoints.js.map
revert

2024-01-23 11:03 UTC, semarche-kaltura commented on samples/playkit-timeline.js
revert

2024-01-23 11:03 UTC, JonathanTGold requested changes
you push .idea files , if it intentionally please move it to separate PR and explanations 
thanks

2024-01-23 11:04 UTC, semarche-kaltura commented on samples/playkit-timeline.js.LICENSE.txt
revert

2024-01-23 11:04 UTC, semarche-kaltura commented on samples/playkit-timeline.js.map
revert

2024-01-23 11:04 UTC, semarche-kaltura commented on samples/playkit-ui-managers.js
revert

2024-01-23 11:04 UTC, semarche-kaltura commented on samples/playkit-ui-managers.js.LICENSE.txt
revert

2024-01-23 11:04 UTC, semarche-kaltura commented on samples/playkit-ui-managers.js.map
revert

2024-01-24 08:20 UTC, closed without merging