chore: export storage managers from player
kaltura/kaltura-player-js pull request #731
Opened 2024-01-31 14:17 UTC by SivanA-Kaltura

### Description of the Changes

TBD

Required for FEC-13504

**Issue:**

**Fix:**

#### Resolves FEC-[Please add the ticket reference here]

2024-02-04 15:17 UTC, JonathanTGold requested changes
We have a dedicated file for global types declarations
https://github.com/kaltura/kaltura-player-js/blob/master/src/types/global/globals.d.ts

2024-02-04 15:20 UTC, JonathanTGold reviewed
what exactly the purpose os exporting these managers? 
I think the  browser storage should be managed only in  kaltura level

2024-02-05 11:35 UTC, SivanA-Kaltura commented
@JonathanTGold For [FEC-13504](https://kaltura.atlassian.net/browse/FEC-13504), I need to add code in a plugin to save a value in session config, and i want to do it through the session storage manager

2024-02-05 11:38 UTC, JonathanTGold approved these changes

2024-02-06 08:45 UTC, merged