feat(FEC-13492): add support for prevent seek
kaltura/kaltura-player-js pull request #747
Opened 2024-03-14 10:24 UTC by lianbenjamin

### Description of the Changes

add support for prevent seek feature.

add listener to `prevent_seek` event and expose a getter so other entities can use it.

#### Resolves FEC-13492

2024-03-14 11:33 UTC, JonathanTGold requested changes
I don’t think the player should be aware of the plugin, the all config should be managed inside the plugin, the plugin has access to the player instance

2024-03-14 11:45 UTC, lianbenjamin commented
@JonathanTGold the plugin is managing the configuration. the player listens to the event fired from the plugin and exposes API so other entities, such as kaltura cue points and timeline, will be able to use the API instead of listening to the event from the plugin.

2024-03-17 09:36 UTC, SivanA-Kaltura requested changes

2024-03-17 09:36 UTC, SivanA-Kaltura commented on src/kaltura-player.ts
> +    this._eventManager.listen(this, 'prevent_seek', (e: FakeEvent) => {
hmmm
should ideally be a const exported from the plugin, but then we'll have a circular dependency...

2024-03-18 08:21 UTC, closed without merging