fix(SUP-38407): [GaTech] [Multistream - V7 Player] Child entries not loading high quality flavor assets
kaltura/kaltura-player-js pull request #851
Opened 2024-09-11 11:49 UTC by Tzipi-kaltura

### Description of the Changes

Please add a detailed description of the change, whether it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

export changeChildQuality function

part of - https://github.com/kaltura/playkit-js/pull/793/files, https://github.com/kaltura/playkit-js-dual-screen/pull/155

#### Resolves [SUP-38407](https://kaltura.atlassian.net/browse/SUP-38407)

2024-09-11 13:43 UTC, semarche-kaltura requested changes
fix lint issues

2024-09-11 13:50 UTC, Tzipi-kaltura commented
> fix lint issues

yes i need to merge first the playkit-js pull request so it will find the function.

2024-09-15 07:36 UTC, MosheMaorKaltura commented on src/kaltura-player.ts
> +  public changeChildQuality(track: any | string): void {
rename to changeQuality

2024-09-15 09:52 UTC, Tzipi-kaltura commented on src/kaltura-player.ts
> +  public changeChildQuality(track: any | string): void {
done

2024-09-15 09:59 UTC, MosheMaorKaltura approved these changes

2024-09-15 10:31 UTC, MosheMaorKaltura approved these changes

2024-09-15 10:32 UTC, merged